// بنك أسئلة المقابلات - مرتب حسب الأهمية لكل نوع شخص
// priority: 1 = حرج (اسأله أولا) ، 2 = مهم ، 3 = تفصيلي ، 4 = إضافي
// type: open | single | multi | number | yesno | yesno_open | scale

const QUESTIONS = [
  // ============================================================
  // الكوتشز (Coaches)
  // ============================================================

  // --- Priority 1: حرج ---
  {
    id: "coach_q1",
    persona: "coach",
    priority: 1,
    section: "أهم المشاكل",
    keywords: "مشاكل · إدارة · ألم",
    text: "ما أكبر 3 مشاكل في إدارة شغلك ككوتش حاليا؟",
    type: "open",
    hint: "لا تفترض أن إدارة العملاء هي المشكلة رقم 1. سيبه يحكي.",
  },
  {
    id: "coach_q2",
    persona: "coach",
    priority: 1,
    section: "الدفع",
    keywords: "فلوس · أدوات · دفع",
    text: "هل تصرف فلوس حاليا على أي أدوات تساعدك في شغل التدريب؟",
    type: "yesno_open",
    followup: "ما الأداة؟ كم السعر؟ ليه دفعت؟ ليه توقفت أو استمريت؟",
    hint: "نبحث عن سلوك دفع حقيقي، مش نية مستقبلية.",
  },
  {
    id: "coach_q3",
    persona: "coach",
    priority: 1,
    section: "البدائل",
    keywords: "منصة · Trainerize · بديل",
    text: "هل جربت أي منصة coaching مثل FitXpert أو Trainerize أو بديل آخر؟ ماذا حدث؟",
    type: "yesno_open",
    followup: "لو جرب: ليه؟ إيه اللي ما عجبكش؟ ليه ما كملتش؟ لو لأ: ما سمعش؟ غالية؟ مفيش عربي؟",
    hint: "لو لم يجرب، اعرف السبب بالضبط.",
  },
  {
    id: "coach_q4",
    persona: "coach",
    priority: 1,
    section: "حجم الشغل",
    keywords: "عملاء · عدد · نوع",
    text: "عندك كام عميل حاليا؟ وأغلبهم Online ولا in-person؟",
    type: "single",
    options: ["أقل من 10", "10 - 20", "20 - 30", "30 - 50", "أكثر من 50"],
    followup: "Online / In-person / Hybrid؟ وكام تقريبا من كل نوع؟",
  },
  {
    id: "coach_q5",
    persona: "coach",
    priority: 1,
    section: "الأدوات الحالية",
    keywords: "أدوات · واتساب · شيتس",
    text: "ما الأدوات التي تستخدمها الآن في شغلك؟",
    type: "multi",
    options: ["WhatsApp", "Excel / Google Sheets", "PDFs", "Google Drive / صور", "Notes", "Instagram", "app جاهز", "ورق / دفتر"],
    followup: "أي جزء بيسبب أكبر ألم؟",
  },

  // --- Priority 2: مهم ---
  {
    id: "coach_q6",
    persona: "coach",
    priority: 2,
    section: "الوقت الضائع",
    keywords: "وقت · إدارة · أكثر",
    text: "ما أكثر جزء يأخذ وقتا في إدارة العملاء؟",
    type: "multi",
    options: ["بناء برنامج التمرين", "بناء الدايت", "المتابعة اليومية", "الرد على الرسائل", "حفظ الصور والقياسات", "تعديل البرامج", "متابعة الالتزام"],
    followup: "احكي ليه ده بالذات بياخد وقت.",
  },
  {
    id: "coach_q7",
    persona: "coach",
    priority: 2,
    section: "متابعة الالتزام",
    keywords: "التزام · متابعة · تمرين",
    text: "كيف تعرف أن العميل نفذ التمرين فعلا؟",
    type: "multi",
    options: ["رسالة منه", "صور / فيديو", "إحساس وتخمين", "مكالمة", "مفيش طريقة واضحة", "app بيسجل التمرين"],
    followup: "عندك أرقام ولا بتعتمد على الإحساس؟",
  },
  {
    id: "coach_q8",
    persona: "coach",
    priority: 2,
    section: "قصة حقيقية",
    keywords: "عميل · التزام · قصة",
    text: "احكي لي عن آخر عميل لم يلتزم بالخطة. ماذا حدث؟",
    type: "open",
    hint: "عايزين قصة حقيقية حصلت، مش رأي عام.",
  },
  {
    id: "coach_q9",
    persona: "coach",
    priority: 2,
    section: "ألم الواتساب",
    keywords: "واتساب · مشكلة · متابعة",
    text: "آخر مرة شعرت أن WhatsApp سبب لك مشكلة في المتابعة، ماذا حصل؟",
    type: "open",
    hint: "رسالة ضاعت؟ معلومة اتدفنت وسط 200 رسالة؟",
  },
  {
    id: "coach_q10",
    persona: "coach",
    priority: 2,
    section: "خسارة عميل",
    keywords: "خسارة · عميل · تواصل",
    text: "هل خسرت عميل بسبب ضعف التواصل أو عدم المتابعة؟ احكي القصة.",
    type: "yesno_open",
    followup: "إيه اللي حصل بالظبط؟ والعميل ده كان بيدفع كام؟",
  },
  {
    id: "coach_q11",
    persona: "coach",
    priority: 2,
    section: "وقت بناء البرنامج",
    keywords: "برنامج · وقت · بناء",
    text: "كم وقت يأخذ منك تجهيز برنامج لعميل جديد؟",
    type: "single",
    options: ["أقل من 15 دقيقة", "15 - 30 دقيقة", "30 - 60 دقيقة", "1 - 2 ساعة", "أكثر من ساعتين"],
    followup: "بتستخدم templates ولا بتبني من الصفر؟",
  },
  {
    id: "coach_q12",
    persona: "coach",
    priority: 2,
    section: "اكتساب العملاء",
    keywords: "عملاء · مصدر · اكتساب",
    text: "كيف يأتي العملاء الجدد؟",
    type: "multi",
    options: ["Instagram", "Referral / ترشيح", "الجيم", "Facebook", "TikTok", "إعلانات مدفوعة", "موقع / Google"],
  },

  // --- Priority 3: تفصيلي ---
  {
    id: "coach_q13",
    persona: "coach",
    priority: 3,
    section: "اليوم العادي",
    keywords: "يوم · روتين · متابعة",
    text: "احكي لي عن يومك العادي ككوتش من أول متابعة العملاء لحد نهاية اليوم.",
    type: "open",
  },
  {
    id: "coach_q14",
    persona: "coach",
    priority: 3,
    section: "بيانات العميل الجديد",
    keywords: "عميل جديد · بيانات · onboarding",
    text: "ما أول معلومات تجمعها من العميل الجديد؟",
    type: "open",
  },
  {
    id: "coach_q15",
    persona: "coach",
    priority: 3,
    section: "إرسال البرنامج",
    keywords: "موبايل · برنامج · إرسال",
    text: "وريني على موبايلك كيف ترسل workout program لعميل.",
    type: "open",
    hint: "شاهده وهو بيعمل ده فعلا، مش بيوصف.",
  },
  {
    id: "coach_q16",
    persona: "coach",
    priority: 3,
    section: "إرسال الدايت",
    keywords: "موبايل · دايت · إرسال",
    text: "وريني كيف ترسل diet plan لعميل.",
    type: "open",
  },
  {
    id: "coach_q17",
    persona: "coach",
    priority: 3,
    section: "الصور والقياسات",
    keywords: "صور · قياسات · حفظ",
    text: "كيف تحفظ progress photos والقياسات؟",
    type: "multi",
    options: ["Google Drive", "ألبوم الموبايل", "WhatsApp", "Excel / Sheets", "app", "مش بحفظها"],
  },
  {
    id: "coach_q18",
    persona: "coach",
    priority: 3,
    section: "بيانات التمرين",
    keywords: "تمرين · بيانات · مجموعات",
    text: "لما تبني workout program، ما البيانات التي تكتبها لكل تمرين؟",
    type: "multi",
    options: ["اسم التمرين", "Sets", "Reps", "Rest", "Tempo", "Weight", "فيديو / صورة", "ملاحظات"],
  },
  {
    id: "coach_q19",
    persona: "coach",
    priority: 3,
    section: "إعادة استخدام البرامج",
    keywords: "برنامج · تكرار · نسخ",
    text: "هل تستخدم نفس البرنامج لأكثر من عميل مع تعديلات؟ كيف؟",
    type: "yesno_open",
  },
  {
    id: "coach_q20",
    persona: "coach",
    priority: 3,
    section: "تكرار التعديل",
    keywords: "برنامج · تغيير · مرات",
    text: "كم مرة تغير البرنامج للعميل الواحد؟",
    type: "single",
    options: ["كل أسبوع", "كل أسبوعين", "كل شهر", "كل 6-8 أسابيع", "نادرا"],
  },
  {
    id: "coach_q21",
    persona: "coach",
    priority: 3,
    section: "بناء الدايت",
    keywords: "دايت · meals · macros",
    text: "كيف تبني الدايت؟ Meals جاهزة أم macros فقط؟",
    type: "single",
    options: ["وجبات جاهزة محددة", "Macros فقط", "الاتنين", "حسب العميل", "مش بعمل دايت"],
  },
  {
    id: "coach_q22",
    persona: "coach",
    priority: 3,
    section: "أكلات مصرية",
    keywords: "أكل · مصري · دايت",
    text: "ما أشهر أكلات مصرية تضعها في الدايت؟",
    type: "open",
  },
  {
    id: "coach_q23",
    persona: "coach",
    priority: 3,
    section: "رمضان",
    keywords: "رمضان · دايت · تعديل",
    text: "كيف تتعامل مع رمضان في البرامج والدايت؟",
    type: "open",
  },
  {
    id: "coach_q24",
    persona: "coach",
    priority: 3,
    section: "تجربة الأدوات",
    keywords: "أداة · تجربة · توقف",
    text: "لماذا جربت أداة معينة قبل كده، وليه استمريت أو توقفت؟",
    type: "open",
  },
  {
    id: "coach_q25",
    persona: "coach",
    priority: 3,
    section: "آخر أداة مدفوعة",
    keywords: "أداة · سعر · دفع",
    text: "ما آخر أداة دفعت لها؟ وكم كان السعر؟",
    type: "open",
  },
  {
    id: "coach_q26",
    persona: "coach",
    priority: 3,
    section: "قيمة الاشتراك",
    keywords: "اشتراك · قيمة · عائد",
    text: "عندما تفكر في دفع اشتراك، ما الذي يجب أن يوفره لك؟",
    type: "open",
  },
  {
    id: "coach_q27",
    persona: "coach",
    priority: 3,
    section: "السعر المقبول",
    keywords: "سعر · شهري · مقبول",
    text: "لو في أداة بتوفرلك وقت وتزود عملاءك، السعر الشهري المقبول كام؟",
    type: "single",
    options: ["أقل من 100 جنيه", "100 - 250", "250 - 500", "500 - 1000", "أكثر من 1000", "بدفع بالدولار"],
  },

  // --- Priority 4: إضافي (AI والختام) ---
  {
    id: "coach_q28",
    persona: "coach",
    priority: 4,
    section: "استخدام AI",
    keywords: "AI · ChatGPT · شهر",
    text: "هل استخدمت ChatGPT أو أي أداة AI في شغلك ككوتش خلال آخر شهر؟",
    type: "yesno_open",
    hint: "نبحث عن استخدام حقيقي متكرر مش فضول مرة واحدة.",
  },
  {
    id: "coach_q29",
    persona: "coach",
    priority: 4,
    section: "آخر استخدام AI",
    keywords: "AI · آخر مرة · موقف",
    text: "احكي لي عن آخر مرة استخدمت فيها AI. ماذا كنت تحاول تعمل؟",
    type: "open",
  },
  {
    id: "coach_q30",
    persona: "coach",
    priority: 4,
    section: "مجال استخدام AI",
    keywords: "AI · مجال · استخدام",
    text: "في أي جزء استخدمت AI؟",
    type: "multi",
    options: ["workout plans", "diet plans", "رسائل العملاء", "محتوى سوشيال", "تحليل progress", "التسعير", "مستخدمتهوش"],
  },
  {
    id: "coach_q31",
    persona: "coach",
    priority: 4,
    section: "الثقة في AI",
    keywords: "AI · ناتج · تعديل",
    text: "هل أخذت الناتج كما هو أم عدلته؟ ما الذي احتجت تعدله؟",
    type: "open",
  },
  {
    id: "coach_q32",
    persona: "coach",
    priority: 4,
    section: "مشاكل AI",
    keywords: "AI · غلط · مشكلة",
    text: "هل حصلت مشكلة بسبب معلومة غلط أو اقتراح غير مناسب من AI؟",
    type: "yesno_open",
  },
  {
    id: "coach_q33",
    persona: "coach",
    priority: 4,
    section: "الدفع لـ AI",
    keywords: "AI · دفع · اشتراك",
    text: "هل تدفع لأي أداة AI حاليا؟ ولماذا تدفع أو لا تدفع؟",
    type: "yesno_open",
  },
  {
    id: "coach_q34",
    persona: "coach",
    priority: 4,
    section: "أمنية AI",
    keywords: "AI · تمني · ثقة",
    text: "ما الشيء الذي تتمنى AI يساعدك فيه لكن لا تثق به حتى الآن؟",
    type: "open",
  },
  {
    id: "coach_q35",
    persona: "coach",
    priority: 4,
    section: "الأمنية الأكبر",
    keywords: "أسهل · أمنية · إدارة",
    text: "لو شيء واحد فقط تتمنى يصبح أسهل في إدارة العملاء، ما هو؟",
    type: "open",
  },
  {
    id: "coach_q36",
    persona: "coach",
    priority: 4,
    section: "ترشيح كوتش",
    keywords: "ترشيح · كوتش · referral",
    text: "هل تعرف كوتشز آخرين يعانون من نفس المشكلة ويمكننا التحدث معهم؟",
    type: "yesno_open",
    hint: "سؤال مهم في نهاية كل مقابلة.",
  },
  {
    id: "coach_q37",
    persona: "coach",
    priority: 4,
    section: "متابعة لاحقة",
    keywords: "follow-up · demo · رجوع",
    text: "هل يمكننا الرجوع لك لاحقا بسؤال أو عرض prototype بسيط؟",
    type: "yesno_open",
  },

  // ============================================================
  // المتدربين / العملاء (Clients)
  // ============================================================

  // --- Priority 1 ---
  {
    id: "client_q1",
    persona: "client",
    priority: 1,
    section: "متابعة الخطة",
    keywords: "خطة · متابعة · أدوات",
    text: "كيف تتابع خطة الكوتش حاليا؟",
    type: "multi",
    options: ["WhatsApp", "PDF", "Excel / Sheets", "صور", "كلام شفهي", "app", "ورق"],
    followup: "اطلب منه يوريك آخر خطة استلمها لو مناسب.",
  },
  {
    id: "client_q2",
    persona: "client",
    priority: 1,
    section: "أكثر جزء مزعج",
    keywords: "مزعج · مربك · تنفيذ",
    text: "ما أكثر جزء مزعج أو مربك في تنفيذ خطة الكوتش؟",
    type: "open",
    hint: "عايزين قصة حصلت، مش رأي عام.",
  },
  {
    id: "client_q3",
    persona: "client",
    priority: 1,
    section: "تجربة app سابقة",
    keywords: "app · كوتش · تجربة",
    text: "هل سبق أن طلب منك كوتش تستخدم app منفصل؟ ماذا حدث؟",
    type: "yesno_open",
    followup: "حمّلته؟ استخدمته؟ توقفت؟ ليه؟",
  },

  // --- Priority 2 ---
  {
    id: "client_q4",
    persona: "client",
    priority: 2,
    section: "فهم التمارين",
    keywords: "تمرين · فيديو · فهم",
    text: "لما تستلم برنامج تمرين، هل بتفهم كل التمارين؟",
    type: "single",
    options: ["أيوة كلها", "أغلبها", "نص ونص", "كتير منها لأ", "بسأل الكوتش كل مرة"],
  },
  {
    id: "client_q5",
    persona: "client",
    priority: 2,
    section: "صعوبة الدايت",
    keywords: "دايت · التزام · صعوبة",
    text: "ما أصعب جزء في الالتزام بالدايت؟",
    type: "multi",
    options: ["تجهيز الأكل", "حساب الكميات", "أكلات مش متوفرة", "الملل", "الخروجات", "السعر", "مش بفهم الخطة"],
  },
  {
    id: "client_q6",
    persona: "client",
    priority: 2,
    section: "التواصل مع الكوتش",
    keywords: "تواصل · كوتش · طريقة",
    text: "كيف بتتواصل مع الكوتش حاليا؟",
    type: "multi",
    options: ["WhatsApp", "مكالمات", "Instagram", "وجها لوجه في الجيم", "app", "مكالمات فيديو"],
  },

  // --- Priority 3 ---
  {
    id: "client_q7",
    persona: "client",
    priority: 3,
    section: "متابعة التقدم",
    keywords: "progress · صور · قياسات",
    text: "كيف بتتابع تقدمك (صور، ميزان، قياسات)؟",
    type: "multi",
    options: ["صور", "الميزان", "المتر / القياسات", "الفورمة في المراية", "الأوزان في الجيم", "مش بتابع"],
  },
  {
    id: "client_q8",
    persona: "client",
    priority: 3,
    section: "أمنية التحسين",
    keywords: "تحسين · أداة · تمني",
    text: "لو حاجة واحدة تتمنى تكون أسهل في تجربتك مع الكوتش، إيه هي؟",
    type: "open",
  },

  // ============================================================
  // إدارة الجيم (Gym Management)
  // ============================================================

  // --- Priority 1 ---
  {
    id: "mgmt_q1",
    persona: "management",
    priority: 1,
    section: "إدارة البيانات",
    keywords: "مدربين · إدارة · نظام",
    text: "كيف بتديروا بيانات المتدربين والمدربين حاليا؟",
    type: "multi",
    options: ["نظام / software", "Excel / Sheets", "ورق / دفتر", "WhatsApp", "كل مدرب لوحده", "ماكينة بصمة / دخول"],
    followup: "في نظام موحد ولا كل واحد بطريقته؟",
  },
  {
    id: "mgmt_q2",
    persona: "management",
    priority: 1,
    section: "أكبر التحديات",
    keywords: "تحديات · إدارة · مشاكل",
    text: "ما أكبر 3 تحديات في إدارة المدربين والمتابعة؟",
    type: "open",
    hint: "سيبه يحكي، ما تفترضش المشكلة.",
  },
  {
    id: "mgmt_q3",
    persona: "management",
    priority: 1,
    section: "نظام الجيم",
    keywords: "software · نظام · أدوات",
    text: "هل بتستخدموا أي نظام أو software لإدارة الجيم؟",
    type: "yesno_open",
    followup: "اسم النظام؟ كام بيكلف؟ راضيين عنه؟",
  },

  // --- Priority 2 ---
  {
    id: "mgmt_q4",
    persona: "management",
    priority: 2,
    section: "فوضى البيانات",
    keywords: "مشاكل · نظام · فوضى",
    text: "هل حصلت مشاكل بسبب عدم وجود نظام موحد؟ احكي مثال.",
    type: "open",
  },
  {
    id: "mgmt_q5",
    persona: "management",
    priority: 2,
    section: "app المدرب",
    keywords: "مدرب · app · عملاء",
    text: "لو مدرب عايز يستخدم app لإدارة عملاءه، ده هيكون مشكلة ولا ميزة للجيم؟",
    type: "single",
    options: ["ميزة كبيرة", "ميزة بسيطة", "محايد", "مشكلة بسيطة", "مشكلة كبيرة"],
    followup: "ليه؟ والجيم عايز يشوف البيانات دي ولا لأ؟",
  },
  {
    id: "mgmt_q6",
    persona: "management",
    priority: 2,
    section: "الدفع للـ software",
    keywords: "فلوس · اشتراك · software",
    text: "هل الجيم بيدفع لأي software حاليا؟ كام؟",
    type: "yesno_open",
  },

  // --- Priority 3 ---
  {
    id: "mgmt_q7",
    persona: "management",
    priority: 3,
    section: "ترك العملاء",
    keywords: "retention · عملاء · ترك",
    text: "ما أكبر سبب المتدربين بيسيبوا الجيم؟",
    type: "multi",
    options: ["السعر", "مفيش نتيجة", "مفيش متابعة", "بعد المكان", "الزحمة", "خدمة سيئة", "ملل"],
  },
  {
    id: "mgmt_q8",
    persona: "management",
    priority: 3,
    section: "جودة المتابعة",
    keywords: "مدرب · جودة · متابعة",
    text: "كيف بتتأكدوا إن المدربين بيتابعوا العملاء بشكل كويس؟",
    type: "open",
  },
];

const PERSONAS = {
  coach: { label: "كوتش", icon: "🏋️", color: "emerald" },
  client: { label: "متدرب", icon: "🙋", color: "sky" },
  management: { label: "إدارة الجيم", icon: "🏢", color: "violet" },
};

const PRIORITY_LABELS = {
  1: { label: "حرج", color: "red" },
  2: { label: "مهم", color: "orange" },
  3: { label: "تفصيلي", color: "blue" },
  4: { label: "إضافي", color: "slate" },
};

const SOURCES = ["Dragon", "ترشيح كوتش", "Instagram", "الجيم", "تواصل مباشر", "أخرى"];
